### ISSUE TITLE
Should only log the longest session every day

### ISSUE THREAD

**Issue by rosenpin** [Yuncun/AbusiveGymReminder#3]
For example, today I went to the gym from 3 PM to 4 PM, the app logged it correctly, after that I was running errands, while passing by the gym for a minute or two. The app recognized it as a gym visit and overrided the correctly logged visit with a 2 minutes visit.
I think the app should not override a longer visit with a shorter visit on the same day.

I tried fixing it myself but as far as I understand you are overriding visits when entering the specified area
```java
if (geofenceTransition == Geofence.GEOFENCE_TRANSITION_DWELL)

            //Log the transition details.
            SharedPrefUtil.updateMainLog(context, "Geofence dwell") ;

            //Update gym status today
            updateLastDayRecord(context);
            rememberGymHabits(context);
            ReminderOracle.doLeaveOnGymArrivalMessage(context, true);
            //sendNotification("GEO FENCE FROM SERVICE", context);

            //Update last visited time
            long time= System.currentTimeMillis();
            SharedPrefUtil.updateLastVisitTime(context, time);

            //Open a visiting counter on this day
            MsgAndDayRecords datasource;
            datasource = MsgAndDayRecords.getInstance();
            datasource.openDatabase();
            DayRecord today = datasource.getLastDayRecord();
            today.startCurrentVisit();
            datasource.updateLatestDayRecordVisits(today.getSerializedVisitsList());
            datasource.closeDatabase();
```

I don't want to make drastic changes to a code I'm not familiar with so it will be swell if you could fix this issue :)

Let me know if I can help with anything

Edit:
I now noticed that the app should be able to track several visits per day.
I am sure that it logged my first visit correctly (about 45 minutes), but it seems like after the second visit the original visit was corrupted. Probably a bug, I will try to add an option to manually change the total time.

**Comment by Yuncun** [comment]
Hi thanks for your update

I made some changes to visit tracking this weekend. You may have gotten the update, and it's possible there was a bug. I also haven't committed the change to github, though I'll do it in one hour from this post, when I get home. 

I've been dealing with a bug where visits don't end, but I'm surprised to see that a visit was removed entirely. When you say the first visit was corrupted, do you mean that it isn't there anymore? Like previously you had "10:00-10:45" and that one disappeared after passing the gym briefly?

Thanks

Manually changing total time is something that is on my eventual todo list (though you are more than welcome to make a pull request!). Right now you can edit the "isGymDay" or "visitedGym" flags easily by pressing on the stat, but editing individual visits is a bit more complicated because it requires a UI. However, if a UI is designed, and the list of Visit objects in DayRecord are updated, then committing the changes are easy - the serialization and database functions are all there.

**Comment by rosenpin** [comment]
Previously I had "4 PM - 4:45 PM"
And now I have 2 visits:
5:09 PM - 5:10 PM
and 
5:12 PM - 5:18 PM

With the total time changed from 44 minutes to 6 minutes

I believe the best and simplest solution to this would be to make the Total time changeable

**Comment by Yuncun** [comment]
I'll try to recreate it tonight and I'll update.

**Comment by rosenpin** [comment]
Awesome thanks!

**Comment by Yuncun** [comment]
Hey Tomer

Sorry this is a late update. I've been working on the edit feature, which has proven to be an interesting UI design challenge. Hopefully will get this out tomorrow.

In the meantime, have you seen this issue occur again? I haven't been able to reproduce it.

**Comment by rosenpin** [comment]
Wow awesome! 
Thank you!
I started working on it a few days ago and didn't have time to finalize it, glad to know you managed to do so.

The issue occurred again yesterday, the visit was logged correctly, I opened the app while still at the gym, after a few minutes the app started logging a new visit while I was still at the gym.
The result was 2 gym visits notifications but only 5 logged minutes *(only the "second" visit)

Waiting anxiously for the update! :)

**Comment by Yuncun** [comment]
I think the issue you describe is a problem with the accuracy of the Google geofences API. I notice sometimes my location skips back and forth. I'm going to work on some kind of algorithm that merges visit intervals if they seem to be from the same visit, and also prevent the user from getting multiple gym hits in a short time.

Thanks for taking a stab at the edit thing. Some of my code may be hard to work with, and the edit thing is kind of complicated because we have to merge overlapping time intervals and all that.

**Comment by rosenpin** [comment]
Got it, thanks for the explanation.
